[tool.kedro]
package_name = "metemcyber_ae8fe20b_62fd_44bf_ac0d_b4f368a35d79"
project_name = "ae8fe20b-62fd-44bf-ac0d-b4f368a35d79"
project_version = "0.17.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/metemcyber_ae8fe20b_62fd_44bf_ac0d_b4f368a35d79 -ra"""
