#! /bin/bash

function usage() {
    echo >&2 "Usage: $0 [init|start|stop|kill]"
    exit 255
}

while getopts 'h' OPT; do
    case ${OPT} in
    h|?) usage;;
    esac
done
shift $((${OPTIND} - 1))

act=$1


case "${act}" in
    init)
        echo "nothing to do dynamically. static params are followings."
        echo "=="
        cat "${ENV_FILE}"
        echo "=="
        ;;
    start)
        ;;
    stop)
        ;;
    kill)
        ;;
    *)
        usage
        ;;
esac
