#! /bin/bash

function usage() {
    echo >&2 "Usage: $0 [init|start|stop|kill]"
    exit 255
}

while getopts 'h' OPT; do
    case ${OPT} in
    h|?) usage;;
    esac
done
shift $((${OPTIND} - 1))

act=$1

BESU_DIR=`cd "${WORKSPACE}/../demo/besu-sample-networks" && pwd`
BESU_LOCKFILE="${BESU_DIR}/.sampleNetworks.lock"

function _besu() {
    (cd "${BESU_DIR}" && $*)
}

case "${act}" in
    init)
        echo "initializing BESU sample network"
        _besu ./remove.sh || echo >&2 "(ignore error)"
        echo "nothing to do dynamically. static params are followings."
        echo "=="
        cat "${ENV_FILE}"
        echo "=="
        ;;
    start)
        if [ -f "${BESU_LOCKFILE}" ]; then
            echo "resuming BESU sample network"
            _besu ./resume.sh || exit 255
        else
            echo "starting BESU sample network"
            _besu ./run.sh || exit 255
        fi
        ;;
    stop)
        echo "suspending BESU sample network"
        _besu ./stop.sh
        ;;
    kill)
        echo "cleaning up BESU sample network"
        _besu ./remove.sh || echo >&2 "(ignore error)"
        ;;
    *)
        usage
        ;;
esac

