[tool.kedro]
package_name = "metemcyber_6d70381b_977a_4f5e_8e8b_72939e84798f"
project_name = "6d70381b-977a-4f5e-8e8b-72939e84798f"
project_version = "0.17.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/metemcyber_6d70381b_977a_4f5e_8e8b_72939e84798f -ra"""
